---
plugin: 
  out_dir: "/media/arvc/data/datasets/TEST_GENERATOR"
  env_dir: "/home/arvc/workSpaces/arvc_ws/src/arvc_dataset_generator/models/enviroment" 
  mod_dir: "/home/arvc/workSpaces/arvc_ws/src/arvc_dataset_generator/models/labeled_models"
  cam_model: "/home/arvc/workSpaces/arvc_ws/src/arvc_dataset_generator/models/camera/model.sdf"
  ground_model_name: "inspection_geom"
  sensor_name: "os_128"
  sensor_topic: "/os1/pointCloud"
  num_models: 20
  num_env: 5
  negative_offset: [-0.5, -0.5, 0.0]
  positive_offset: [0.5, 0.5, 0.0]
  positive_dist: [10.0, 10.0, 5.0]
  negative_dist: [-10.0, -10.0, 0.0]
  min_scale: [0.5, 0.1, 0.1]
  max_scale: [2.0, 0.5, 0.5]
  rand_mode: uniform
  pc_binary: true
  debug_msgs: false