common: 
  out_dir: "/home/fran/datasets/icinco/03"
  num_env: 1000
  save_pcd: true
  pcd_binary: true
  paused: false
  debug_msgs: false

collision:
  model: "truss_crossed_555_2.000.20_t_i_u_s" # model to compute the collisions with the sensor

sensor:
  name: "os_128"
  topic: "/os1/pointCloud"
  collision_offset: 1 # % to increase the collision box of the original sensor

poses:
  offset: 2.0
  rand_mode: uniform # uniform, gaussian
