---
plugin: 
  out_dir: "/media/arvc/data/datasets/TEST_GENERATOR"
  cam_model: "/home/arvc/workSpaces/arvc_ws/src/arvc_dataset_generator/models/camera/model.sdf"
  fixed_model_name: "reticular_structure"
  mobile_model_name: "os_128"
  sensor_name: "os_128"
  sensor_topic: "/os1/pointCloud"
  cam_name: "camera_test"
  num_models: 20
  num_env: 10000
  negative_offset: [-0.5, -0.5, 0.0]
  positive_offset: [0.5, 0.5, 0.0]
  positive_dist: [2.5, 2.5, 2.5]
  negative_dist: [-2.5, -2.5, 0.0]
  min_scale: [0.5, 0.1, 0.1]
  max_scale: [2.0, 0.5, 0.5]
  rand_mode: uniform
  pc_binary: true
  debug_msgs: true
  paused: true